### ISSUE TITLE
pretrained weight mismatch

### ISSUE THREAD

**Issue by robvoid** [LoraLinH/Gramformer#3]
the download link of ‘jhu weight’ is Gradformer_UCF.pth，and the test results of it on UCF is much better than JHU
the download link of ‘ucf weight' is MS2_UCF.pth， failed to load with different keys

**Comment by LoraLinH** [comment]
Sorry for uploading the wrong model. It has been corrected.

**Comment by shehzadkhanofficial** [comment]
Got it, thank you for your help and prompt response highly appreciated.
